name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v4
      - name: Copiar .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Atualizando o composer
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Instalando dependências
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Gerando a chave da aplicação
        run: php artisan key:generate
      - name: Definindo permissões de escrita
        run: chmod -R 777 storage bootstrap/cache
      - name: Criando banco de dados de teste
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Executando testes de unidade e integração
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
      - name: PHPStan
        run: ./vendor/bin/phpstan analyse app
      - name: Codesniffer
        run: ./vendor/bin/phpcs --standard=PSR12 app
